name: unisba_sisfo
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  page_transition: ^2.0.9
  fluttertoast: ^8.0.9
  dio: ^4.0.6
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.15
  circular_bottom_navigation: ^2.2.0
  persistent_bottom_nav_bar: any
  carousel_slider: ^4.1.1
  badges: ^2.0.3
  webview_flutter: ^3.0.4
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Segoe     
      fonts:
        - asset: assets/fonts/segoe.ttf